// <auto-generated />
namespace ExchangeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_nomenclature : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_nomenclature));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101557256_new_nomenclature"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
