// <auto-generated />
namespace ExchangeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class all_models_10022018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(all_models_10022018));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101819067_all_models_10.02.2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
