// <auto-generated />
namespace ExchangeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180210_added_level : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180210_added_level));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101510002_20180210_added_level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
